#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# check_patterns.py — CI-side pattern VALIDATOR (no Ghidra).
#
# This is the VALIDATE half of tools/derive_patterns.py, ported off Ghidra so a
# GitHub Action (.github/workflows/watch-steam.yml) can run it against a
# freshly-downloaded steamclient.so. It does NOT re-derive moved patterns — that
# stays in derive_patterns.py (Ghidra). It only answers the question the daily
# monitor needs:
#
#   "Do the CURRENT patterns from src/patterns.hpp still resolve UNIQUELY in this
#    binary, and are the package-0 finder's runtime anchors still present?"
#
# i.e. the A.1 (hash bump) vs A.2 (pattern moved) vs C (finder anchor moved)
# distinction from docs/maintenance.md, computed in pure Python (no Ghidra, no
# capstone, no running the .so).
#
# Pattern source of truth: src/patterns.hpp is PARSED at runtime — patterns are
# never re-hardcoded here, so this can't drift from what the binary ships. The
# two finder anchors are NOT in patterns.hpp (the finder derives them at runtime
# from stable struct offsets); they are mirrored here from
# src/hooks/package_zero_finder.cpp exactly as derive_patterns.py mirrors them.
#
# Usage:
#   python3 tools/check_patterns.py <steamclient.so> [--hpp src/patterns.hpp]
#                                                    [--json result.json]
#
# Exit codes (the workflow branches on these):
#   0  CLEAN             all criticals UNIQUE, finder anchors present,
#                        ShaderDepot UNIQUE  -> A.1: PR the hash, no issue.
#   2  NONCRITICAL_MOVED criticals + anchors OK but ShaderDepot moved
#                        -> A.1: PR the hash AND open a ShaderDepot issue.
#   3  BLOCKING          a critical pattern, a finder anchor, or the DepotKey
#                        RTTI ground-truth (§15/#19: exactly one CConfigStore
#                        vtable slot must match kDepotKeyFnPattern) failed
#                        -> open an issue (A.2 / C); do NOT whitelist.
#   1  usage / I/O / unparseable-binary error.
import argparse
import bisect
import hashlib
import json
import os
import re
import struct
import sys


def emit_rvas_file(result, out_dir, steam_version):
    """Write <out_dir>/<sha256>.yaml with the RVAs check_patterns already derived
    — one file per build, keyed by hash, mirroring steam-monitor's <sha256>.toml
    layout. The runtime resolver consumes these RVA-first (docs/rva-feed-design.md);
    src/patterns.hpp stays the fallback. Only UNIQUE, non-diagnostic hooks are
    written (a moved/ambiguous hook is omitted so that hook falls back to its byte
    pattern). Hand-serialized for a stable, diff-friendly, dependency-free output.
    Caller must gate on a non-BLOCKING verdict."""
    os.makedirs(out_dir, exist_ok=True)
    sha = result["steamclient_sha256"]

    hook_lines = []
    for label, info in result["hooks"].items():          # insertion order = stable
        if info.get("tier") == "diagnostic":
            continue
        if info.get("status") == "UNIQUE" and info.get("rvas"):
            hook_lines.append('  %s: "%s"' % (label, info["rvas"][0]))

    out = [
        "# Auto-generated by tools/check_patterns.py --emit-rvas. Do NOT edit by hand.",
        "# Per-build hook RVAs (file vaddrs) keyed by steamclient.so SHA-256,",
        "# consumed RVA-first by the runtime resolver (docs/rva-feed-design.md).",
        "# Byte patterns in src/patterns.hpp remain the fallback.",
        'steamclient_sha256: "%s"' % sha,
    ]
    if steam_version:
        out.append("steam_version: %s" % steam_version)
    out.append("hooks:" if hook_lines else "hooks: {}")
    out.extend(hook_lines)

    rt = result.get("rtti", {})
    if rt.get("status") == "UNIQUE":
        out += ["depotkey_rtti:",
                '  class: "%s"' % rt["class"],
                "  slot: %d" % rt["slot"],
                '  rva: "%s"' % rt["rva"]]

    ci = result.get("finder", {}).get("cache_idiom", {})
    if ci.get("status") == "PRESENT" and ci.get("sites"):
        out += ["finder:",
                '  cache_global_disp: "%s"' % ci["sites"][0]["disp32"]]

    path = os.path.join(out_dir, sha + ".yaml")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    return path

# ── hook classification ──────────────────────────────────────────────────────
# Keyed by the patterns.hpp constant name. The display name is what the
# workflow puts in the issue/PR. "expect" is how many matches mean OK.
#
#   CRITICAL    — must resolve to exactly ONE site or the hook can't install.
#                 A miss/ambiguity here blocks the whitelist (A.2).
#   NONCRITICAL — a miss loses an optional feature but installs still work, so
#                 the hash can still be whitelisted; we open an issue + auto-derive
#                 so it gets fixed. ShaderDepot (per-game shader skip) and Reconcile
#                 (NotifyLicensesUpdated, the no-restart Add Game path — a miss only
#                 costs a Steam restart, degrades cleanly) live here. Which of these
#                 resolved on a build is recorded per-hash in updates.yaml (`caps:`)
#                 so LumaDeck's update gate knows what a build would lose.
#   DIAGNOSTIC  — never blocks, never opens an issue; reported for information
#                 only. LoadPackage (opt-in, multi-match EXPECTED — 3 candidates,
#                 runtime picks index 0) and BuildDep (disabled since SLSsteam
#                 20260714 owns BuildDepotDependency and hooks it first) live here.
CRITICAL = {
    "kDepotKeyFnPattern":          "DepotKey",
    "kGmrcFunctionPattern":        "GMRC",
}
NONCRITICAL = {
    "kShaderCacheDepotPattern":    "ShaderDepot",
    "kNotifyLicensesUpdatedPattern": "Reconcile",
}
# Short capability token per non-critical const, written into updates.yaml as a
# `# caps: <token>=ok|moved ...` comment next to each whitelisted hash. LumaDeck
# text-scans it to decide, per build, whether an update would lose a feature
# (shader pre-cache skip / no-restart Add Game). `ok` = resolved uniquely on this
# build; `moved` = the pattern didn't resolve (the feature degrades, non-blocking).
CAP_TOKEN = {
    "kShaderCacheDepotPattern":      "shader",
    "kNotifyLicensesUpdatedPattern": "reconcile",
}
DIAGNOSTIC = {
    "kLoadPackagePattern": "LoadPackage",
    # BuildDep is disabled at runtime since SLSsteam 20260714 owns
    # BuildDepotDependency (it hooks the prologue in memory first). We no longer
    # install the hook, so a pattern miss must NOT block the whitelist. Validate
    # for information only; re-promote to CRITICAL if BuildDep is re-enabled.
    "kBuildDepotDependencyPattern": "BuildDep",
}

# ── DepotKey RTTI ground-truth (§15, #19) ────────────────────────────────────
# The runtime (Rtti::ResolveVtableSlotBySignature) no longer trusts a hardcoded
# slot: it finds CConfigStore's vtable by RTTI, then DERIVES the accessor's slot
# by matching kDepotKeyFnPattern inside the vtable. Mirror that walk here so the
# cron confirms, per build, that the derivation resolves to EXACTLY ONE slot —
# and records which (a change from 6 = Valve reordered the vtable; the runtime
# handles it, but we want to see it). Zero or multiple => BLOCKING (the runtime
# primary path can't resolve uniquely; do not whitelist).
RTTI_DEPOTKEY = {"class": "12CConfigStore", "const": "kDepotKeyFnPattern",
                 "label": "DepotKey", "max_slots": 40}

# Name-derived resolution — the SECOND opinion, and the only one here that reads
# no byte of the target function. Mirrors Rtti::ResolveVtableSlotByName (and
# download.lua): find the slot of the interface-MAP class whose function
# references the method name as a string, then apply that index to the concrete
# class. Verified on build bc54101b29 by tools/experiment_ifacemap_slot.py:
# "GetBinary" -> map slot 6 -> CConfigStore 0x11a4500, the pattern's own answer.
#
# Why it belongs in CI: the runtime uses it as its last-resort resolver, and a
# resolver nothing validates is a parachute nobody has opened. It is also what
# makes `agrees_with_pattern` mean something — that field compares the pattern
# with itself, so it is true by construction and reports nothing.
BYNAME_DEPOTKEY = {"map_class": "21IClientConfigStoreMap", "method": "GetBinary",
                   "impl_class": "12CConfigStore", "label": "DepotKey-byname",
                   "max_slots": 64,
                   # Max distance from a slot's entry for a reference to count as
                   # "inside it". The same name is referenced from unrelated code
                   # far from this vtable; attributing that would pick a wrong slot.
                   "max_fn_size": 512}

# GMRC's RESCUE path, which nothing validated until now — and a rescue only runs
# once the pattern has already missed, i.e. exactly when there is no second
# opinion left to catch it being wrong. Two things the Deck depends on here:
#
#   (a) the job-name string anchor: it must exist and be referenced from EXACTLY
#       ONE site, or it identifies nothing (the v0.10.3 LoadPackage lesson);
#   (b) .eh_frame_hdr: since 2026-09-07 the runtime turns that site into the
#       function ENTRY by looking it up in the binary's own sorted function table
#       (src/eh_frame.hpp) instead of walking backwards. A build whose header
#       encodings this parser does not implement makes the runtime fail closed and
#       fall back to the walk-back and its two documented failure modes — silently,
#       unless CI says so.
GMRC_XREF = {"string": "ContentServerDirectory.GetManifestRequestCode#1",
             "const": "kGmrcFunctionPattern", "label": "GMRC"}

# ── finder anchors (§13.5) — mirrored from package_zero_finder.cpp ────────────
# (a) cache-access idiom, anchored on the 0xc58 tree-root offset of
#     CPackageInfoCache:  lea r1,[GOT+X] ; mov r2,[r1] ; mov r3,[r2+0xc58].
#     The 0xc58 disp32 little-endian (58 0C 00 00) is the unambiguous needle;
#     we validate the lea/mov/mov shape backwards from each hit.
# (b) GMRC prologue tail that survives the hook detour — the bytes DeriveGotBase
#     scans for.
CACHE_ROOT_OFFSET = 0xC58
CACHE_IDIOM_NEEDLE = "58 0C 00 00"
GMRC_PROLOGUE_TAIL = "55 89 E5 57 56 53 81 EC 10 01 00 00 8B 7D 08 8B 4D 20"


# ── patterns.hpp parsing ─────────────────────────────────────────────────────

def parse_patterns_hpp(path):
    """Extract {constant_name: "byte pattern"} for every kXxxPattern in the
    header. The decls look like:
        inline constexpr const char* kDepotKeyFnPattern =
            "55 57 56 ...";
    so we match the name and the (possibly next-line) string literal."""
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    out = {}
    for m in re.finditer(r'(\bk\w+Pattern)\s*=\s*"([0-9A-Fa-f? ]+)"', text):
        out[m.group(1)] = m.group(2).strip()
    return out


# ── ELF: executable segments ─────────────────────────────────────────────────

def load_exec_segments(path):
    """Return [(vaddr, bytes), ...] for every PT_LOAD|PF_X segment of a 32-bit
    little-endian ELF. vaddr is the segment's p_vaddr, which for a shared object
    (image base 0) IS the RVA base — so a match at byte offset `o` within the
    segment has RVA = vaddr + o, matching derive_patterns.py's RVA reporting."""
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"\x7fELF":
        raise ValueError("not an ELF file")
    ei_class, ei_data = data[4], data[5]
    if ei_class != 1:
        raise ValueError("not ELFCLASS32 (steamclient.so is 32-bit)")
    if ei_data != 1:
        raise ValueError("not little-endian")
    # Elf32_Ehdr: e_phoff@0x1C(4), e_phentsize@0x2A(2), e_phnum@0x2C(2)
    e_phoff = struct.unpack_from("<I", data, 0x1C)[0]
    e_phentsize = struct.unpack_from("<H", data, 0x2A)[0]
    e_phnum = struct.unpack_from("<H", data, 0x2C)[0]
    PT_LOAD, PF_X = 1, 0x1
    segs = []
    for i in range(e_phnum):
        off = e_phoff + i * e_phentsize
        # Elf32_Phdr: p_type(0) p_offset(4) p_vaddr(8) ... p_filesz(16) p_flags(24)
        p_type, p_offset, p_vaddr = struct.unpack_from("<III", data, off)
        p_filesz = struct.unpack_from("<I", data, off + 16)[0]
        p_flags = struct.unpack_from("<I", data, off + 24)[0]
        if p_type == PT_LOAD and (p_flags & PF_X):
            segs.append((p_vaddr, data[p_offset:p_offset + p_filesz]))
    if not segs:
        raise ValueError("no executable PT_LOAD segment found")
    return segs


# ── byte-pattern scanning ────────────────────────────────────────────────────

def pattern_to_regex(patstr):
    """Compile a 'AA BB ?? CC' pattern into a bytes regex: concrete bytes are
    escaped literally, '??' becomes '.'. DOTALL is essential so a wildcard can
    match a 0x0A byte (without it, '.' would skip newlines and miss matches)."""
    parts = []
    for tok in patstr.split():
        if tok.startswith("?"):
            parts.append(b".")
        else:
            parts.append(re.escape(bytes([int(tok, 16)])))
    return re.compile(b"".join(parts), re.DOTALL)


def scan_rvas(segments, patstr):
    """Return the list of RVAs where `patstr` matches across all exec segments.
    Patterns are long, distinctive prologues, so non-overlapping finditer is
    sufficient (overlaps are not a real concern at 28+ bytes)."""
    rx = pattern_to_regex(patstr)
    hits = []
    for vaddr, buf in segments:
        for m in rx.finditer(buf):
            hits.append(vaddr + m.start())
    return hits


def verify_cache_idiom(segments):
    """Find every valid cache-access idiom and return [(rva, lea_disp32), ...].
    For each `58 0C 00 00` needle the layout backwards is:
        base+0 = 8D (lea r1,[GOT+disp32])   base+2..5 = disp32
        base+6 = 8B (mov r2,[r1])
        base+8 = 8B (mov r3,[r2+0xc58])      base+10 = 58 0C 00 00 (the needle)
    so base = needle_off - 10. Validate the 8D/8B/8B shape before accepting."""
    needle = bytes(int(t, 16) for t in CACHE_IDIOM_NEEDLE.split())
    out = []
    for vaddr, buf in segments:
        start = 0
        while True:
            o = buf.find(needle, start)
            if o < 0:
                break
            start = o + 1
            base = o - 10
            if base < 0:
                continue
            if buf[base] == 0x8D and buf[base + 6] == 0x8B and buf[base + 8] == 0x8B:
                disp = struct.unpack_from("<i", buf, base + 2)[0]
                out.append((vaddr + base, disp))
    return out


# ── status helpers ───────────────────────────────────────────────────────────

def classify_hit_count(n):
    if n == 1:
        return "UNIQUE"
    if n == 0:
        return "NOT_FOUND"
    return "AMBIGUOUS"


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# ── DepotKey RTTI ground-truth (static mirror of Rtti::ResolveVtableSlotBySignature)

def _load_sections(path):
    """Parse ELF32 section headers into {name: (sh_addr, sh_offset, sh_size)}
    plus the raw file bytes. Pure struct parsing — no pyelftools — to keep this
    validator dependency-free like the rest of the file."""
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"\x7fELF" or data[4] != 1:
        raise ValueError("not an ELF32 object")
    e_shoff = struct.unpack_from("<I", data, 0x20)[0]
    e_shentsize = struct.unpack_from("<H", data, 0x2E)[0]
    e_shnum = struct.unpack_from("<H", data, 0x30)[0]
    e_shstrndx = struct.unpack_from("<H", data, 0x32)[0]
    if not e_shoff or not e_shnum:
        raise ValueError("no section headers")

    def shdr(i):
        o = e_shoff + i * e_shentsize
        name, _typ, _flags, addr, off, size = struct.unpack_from("<IIIIII", data, o)
        return name, addr, off, size

    strtab_off = shdr(e_shstrndx)[2]
    secs = {}
    for i in range(e_shnum):
        nmoff, addr, off, size = shdr(i)
        end = data.index(b"\x00", strtab_off + nmoff)
        nm = data[strtab_off + nmoff:end].decode("latin1")
        secs[nm] = (addr, off, size)
    return data, secs


def _vtable_funcs_va(data, secs, mangled):
    """type-name (.rodata) -> type_info -> vtable header -> VA of slot 0.

    i386 relocations are REL: the addend is stored in place, so the file already
    holds the vaddrs. Same walk Rtti::FindTypeVtable does live, and it reads no
    code byte. Returns (va, note); va is None on failure."""
    if ".rodata" not in secs or ".data.rel.ro" not in secs:
        return None, "missing .rodata/.data.rel.ro"

    ro_a, ro_o, ro_s = secs[".rodata"]
    i = data[ro_o:ro_o + ro_s].find(mangled.encode() + b"\x00")
    if i < 0:
        return None, "type-name not found"
    name_va = ro_a + i

    drr_a, drr_o, drr_s = secs[".data.rel.ro"]
    drr = data[drr_o:drr_o + drr_s]
    ti_field = None
    for off in range(0, len(drr) - 4, 4):
        if struct.unpack_from("<I", drr, off)[0] == name_va:
            ti_field = drr_a + off
            break
    if ti_field is None:
        return None, "type_info not found"
    typeinfo_va = ti_field - 4

    for off in range(0, len(drr) - 8, 4):
        if (struct.unpack_from("<I", drr, off)[0] == 0
                and struct.unpack_from("<I", drr, off + 4)[0] == typeinfo_va):
            return drr_a + off + 8, "ok"
    return None, "vtable not found"


def _read_va(data, secs):
    ranges = [(a, o, s) for (a, o, s) in secs.values() if a and s]

    def read_va(va, n):
        for a, o, s in ranges:
            if a <= va < a + s and va + n <= a + s:
                return data[o + (va - a): o + (va - a) + n]
        return b""
    return read_va


def _got_base_consensus(data, secs):
    """`E8 <rel32>; 05 <imm32>` = call get_pc_thunk.ax; add eax,GOT. The thunk
    returns the address AFTER the call, so got = (va of the 05) + imm32. One
    module-wide value, so the right answer dominates. Port of
    DeriveGotBaseConsensus (gmrc_xref_core.hpp)."""
    if ".text" not in secs:
        return None
    a, o, s = secs[".text"]
    tx = data[o:o + s]
    votes = {}
    i, n = 0, len(tx) - 10
    while i < n:
        j = tx.find(b"\xE8", i)
        if j < 0 or j > n:
            break
        if tx[j + 5] == 0x05:
            imm = struct.unpack_from("<i", tx, j + 6)[0]
            va = (a + j + 5 + imm) & 0xFFFFFFFF
            votes[va] = votes.get(va, 0) + 1
        i = j + 1
    if not votes:
        return None
    return max(votes.items(), key=lambda kv: kv[1])[0]


def eh_frame_starts(path):
    """Sorted function-start table from .eh_frame_hdr. Port of the runtime
    src/eh_frame.cpp, and of tools/experiment_eh_frame.py which measured it
    viable on build bc54101b29.

    Only the fixed-size encodings gcc emits here are implemented; anything else
    returns an error rather than being guessed at, exactly like the C++ does.
    Returns (starts, info, note); starts is None on failure."""
    try:
        data, secs = _load_sections(path)
    except (OSError, ValueError) as e:
        return None, {}, "load:%s" % e
    if ".eh_frame_hdr" not in secs:
        return None, {}, "no .eh_frame_hdr"
    hdr_va, hdr_off, _hdr_size = secs[".eh_frame_hdr"]

    def read_enc(off, enc):
        fmt, app = enc & 0x0F, enc & 0x70
        if fmt == 0x03:                      # udata4
            v = struct.unpack_from("<I", data, off)[0]
        elif fmt == 0x0B:                    # sdata4
            v = struct.unpack_from("<i", data, off)[0]
        else:
            raise ValueError("unimplemented value encoding 0x%02x" % enc)
        at = hdr_va + (off - hdr_off)
        if app == 0x00:                      # absptr
            base = 0
        elif app == 0x10:                    # pcrel
            base = at
        elif app == 0x30:                    # datarel
            base = hdr_va
        else:
            raise ValueError("unimplemented encoding application 0x%02x" % enc)
        return (base + v) & 0xFFFFFFFF, off + 4

    info = {"version": data[hdr_off], "eh_frame_ptr_enc": data[hdr_off + 1],
            "fde_count_enc": data[hdr_off + 2], "table_enc": data[hdr_off + 3]}
    if info["version"] != 1:
        return None, info, "version %d unsupported" % info["version"]
    try:
        off = hdr_off + 4
        _ehf, off = read_enc(off, info["eh_frame_ptr_enc"])
        count, off = read_enc(off, info["fde_count_enc"])
        starts = []
        prev = 0
        for _ in range(count):
            loc, off = read_enc(off, info["table_enc"])
            _fde, off = read_enc(off, info["table_enc"])
            if loc < prev:
                return None, info, "table not sorted"
            prev = loc
            starts.append(loc)
    except (ValueError, struct.error) as e:
        return None, info, str(e)
    info["count"] = len(starts)
    return starts, info, "ok"


def gmrc_xref_derive(path, anchor):
    """Mirror of the runtime GMRC rescue (src/gmrc_xref.cpp): job-name string ->
    GOT base by consensus -> the UNIQUE `lea reg,[got+disp32]` referencing it ->
    the containing function's entry from .eh_frame_hdr.

    Fail-closed like the runtime: a string that is absent, or referenced from more
    than one site, resolves to nothing rather than to a guess.
    Returns (info, note)."""
    try:
        data, secs = _load_sections(path)
    except (OSError, ValueError) as e:
        return {"status": "LOAD_FAILED"}, "load:%s" % e
    if ".text" not in secs or not secs[".text"][2]:
        return {"status": "NO_TEXT"}, "no .text"

    needle = anchor.encode() + b"\x00"
    s_va = None
    for _nm, (a, o, sz) in sorted(secs.items()):
        if not a or not sz:
            continue
        j = data[o:o + sz].find(needle)
        if j >= 0:
            s_va = a + j
            break
    if s_va is None:
        return {"status": "STRING_NOT_FOUND"}, "job-name string absent"

    got = _got_base_consensus(data, secs)
    if got is None:
        return {"status": "NO_GOT"}, "could not derive GOT base"

    tx_a, tx_o, tx_s = secs[".text"]
    tx = data[tx_o:tx_o + tx_s]
    needle32 = struct.pack("<I", (s_va - got) & 0xFFFFFFFF)
    sites, i = [], 0
    while True:
        j = tx.find(needle32, i)
        if j < 0:
            break
        i = j + 1
        if j < 2 or tx[j - 2] != 0x8D:
            continue
        modrm = tx[j - 1]
        if (modrm & 0xC0) != 0x80 or (modrm & 0x07) == 0x04:
            continue
        sites.append(tx_a + j - 2)

    out = {"string_rva": "0x%x" % s_va, "got": "0x%x" % got,
           "sites": ["0x%x" % v for v in sites]}
    if len(sites) != 1:
        # The whole point of a string anchor is that it identifies ONE function.
        out["status"] = "AMBIGUOUS" if sites else "NO_SITE"
        return out, "%d referencing site(s), need exactly 1" % len(sites)

    site = sites[0]
    starts, eh_info, eh_note = eh_frame_starts(path)
    out["eh_frame"] = {"note": eh_note, **{k: v for k, v in eh_info.items()}}
    if starts is None:
        out["status"] = "NO_EH_FRAME"
        return out, "site 0x%x found but .eh_frame_hdr unusable: %s" % (site, eh_note)

    i = bisect.bisect_right(starts, site) - 1
    if i < 0:
        out["status"] = "NOT_IN_A_FUNCTION"
        return out, "site 0x%x precedes every function" % site
    end = starts[i + 1] if i + 1 < len(starts) else (tx_a + tx_s)
    if site >= end:
        out["status"] = "NOT_IN_A_FUNCTION"
        return out, "site 0x%x is past the last function" % site

    out["status"] = "UNIQUE"
    out["rva"] = "0x%x" % starts[i]
    out["fn_size"] = end - starts[i]
    return out, "ok"


def rtti_derive_slot_byname(path, map_class, method, impl_class,
                            max_slots=64, max_fn_size=512):
    """Derive the vtable slot from the METHOD NAME. Mirrors the runtime
    Rtti::ResolveVtableSlotByName; see BYNAME_DEPOTKEY above for the why.

    SLSsteam builds the whole name->index map for 37 interfaces
    (Decompiler::parseInterfaceMapBase); one entry is needed here, so the question
    is inverted — not "which strings does each slot mention?" but "which slot
    mentions THIS address?". That needs no disassembler: in i386 PIC a string is
    referenced as `lea reg,[got+disp32]`, so with the string address S and the GOT
    base it is a search for `8D <modrm mod=10> <disp32>` with disp32 == S - GOT.

    Returns (info, note). info["status"] is UNIQUE / NOT_RESOLVED / <error>."""
    try:
        data, secs = _load_sections(path)
    except (OSError, ValueError) as e:
        return {"status": "LOAD_FAILED"}, "load:%s" % e
    if ".text" not in secs or not secs[".text"][2]:
        return {"status": "NO_TEXT"}, "no .text"

    # (1) every exact, NUL-terminated occurrence of the method name. The full
    # terminator matters: "GetBinary" is a prefix of "GetBinaryWatermarked", and
    # Steam emits this name table more than once (four hits on bc54101b29), so
    # the right one is chosen by WHICH slot references it, not by being first.
    needle = method.encode() + b"\x00"
    str_vas = []
    for _nm, (a, o, sz) in sorted(secs.items()):
        if not a or not sz:
            continue
        blob = data[o:o + sz]
        start = 0
        while True:
            j = blob.find(needle, start)
            if j < 0:
                break
            start = j + 1
            if j == 0 or blob[j - 1] == 0:      # NUL before too: not a tail
                str_vas.append(a + j)
    if not str_vas:
        return {"status": "NOT_RESOLVED"}, "method name %r not found as a string" % method

    got = _got_base_consensus(data, secs)
    if got is None:
        return {"status": "NOT_RESOLVED"}, "could not derive GOT base"

    map_vt, note = _vtable_funcs_va(data, secs, map_class)
    if map_vt is None:
        return {"status": "NOT_RESOLVED"}, "%s: %s" % (map_class, note)

    read_va = _read_va(data, secs)
    tx_a, tx_o, tx_s = secs[".text"]
    tx = data[tx_o:tx_o + tx_s]

    slots = []
    for k in range(max_slots):
        b = read_va(map_vt + k * 4, 4)
        if len(b) < 4:
            break
        fn = struct.unpack_from("<I", b, 0)[0]
        if not (tx_a <= fn < tx_a + tx_s):
            break                                # first non-code entry = end
        slots.append((fn, k))
    if not slots:
        return {"status": "NOT_RESOLVED"}, "%s vtable has no code slots" % map_class
    slots.sort()

    # (2) which slot references which occurrence.
    hits = {}
    for s_va in str_vas:
        needle32 = struct.pack("<I", (s_va - got) & 0xFFFFFFFF)
        i = 0
        while True:
            j = tx.find(needle32, i)
            if j < 0:
                break
            i = j + 1
            if j < 2 or tx[j - 2] != 0x8D:
                continue
            modrm = tx[j - 1]
            if (modrm & 0xC0) != 0x80 or (modrm & 0x07) == 0x04:
                continue
            ref = tx_a + j - 2
            owner = None
            for fn, k in slots:
                if fn <= ref:
                    owner = (fn, k)
                else:
                    break
            if owner and ref - owner[0] <= max_fn_size:
                hits.setdefault(owner[1], []).append(s_va)
    if not hits:
        return {"status": "NOT_RESOLVED"}, "no %s slot references %r" % (map_class, method)

    # Overloads have one string EACH, in consecutive slots; a bare name means the
    # first, which is what SLSsteam's table does (name, name2, name3...). The
    # sibling slot is a DIFFERENT function, so this tie-break is load-bearing.
    slot = min(hits)

    impl_vt, note = _vtable_funcs_va(data, secs, impl_class)
    if impl_vt is None:
        return {"status": "NOT_RESOLVED"}, "%s: %s" % (impl_class, note)
    b = read_va(impl_vt + slot * 4, 4)
    if len(b) < 4:
        return {"status": "NOT_RESOLVED"}, "%s has no slot %d" % (impl_class, slot)
    fn_rva = struct.unpack_from("<I", b, 0)[0]

    return ({"status": "UNIQUE", "map_class": map_class, "method": method,
             "slot": slot, "rva": "0x%x" % fn_rva,
             "overloads": sorted(hits),
             "name_sites": ["0x%x" % v for v in str_vas]},
            "ok")


def rtti_derive_slot(path, mangled, patstr, max_slots=40):
    """Walk RTTI for `mangled`: type-name string (.rodata) -> type_info ->
    vtable (.data.rel.ro; i386 REL relocations store the addend = target vaddr
    in-place, so the file already holds the vaddrs), then scan up to `max_slots`
    slots and return [(slot_index, fn_rva), ...] for every slot whose target
    function's prologue matches `patstr`. This is the exact invariant the runtime
    derive-by-signature relies on. Returns (matches, note); matches is None on a
    walk failure (vtable not locatable), with `note` explaining which step."""
    try:
        data, secs = _load_sections(path)
    except (OSError, ValueError) as e:
        return None, "load:%s" % e

    vt_funcs, note = _vtable_funcs_va(data, secs, mangled)
    if vt_funcs is None:
        return None, note
    read_va = _read_va(data, secs)

    rx = pattern_to_regex(patstr)
    matches = []
    for k in range(max_slots):
        fnb = read_va(vt_funcs + k * 4, 4)
        if len(fnb) < 4:
            break
        fn = struct.unpack_from("<I", fnb, 0)[0]
        prol = read_va(fn, 64)
        if prol and rx.match(prol):
            matches.append((k, fn))
    return matches, "ok"


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="Validate lumalinux patterns against a steamclient.so (no Ghidra).")
    ap.add_argument("steamclient", help="path to the ubuntu12_32/steamclient.so to check")
    ap.add_argument("--hpp", default="src/patterns.hpp",
                    help="path to src/patterns.hpp (pattern source of truth)")
    ap.add_argument("--json", default=None,
                    help="optional path to write the machine-readable result")
    ap.add_argument("--emit-rvas", metavar="DIR", default=None,
                    help="on a non-BLOCKING verdict, write DIR/<sha256>.yaml with the "
                         "derived hook RVAs (the RVA-first feed; docs/rva-feed-design.md)")
    ap.add_argument("--steam-version", default=None,
                    help="optional Steam client version recorded in the emitted RVA file")
    args = ap.parse_args()

    try:
        segments = load_exec_segments(args.steamclient)
        patterns = parse_patterns_hpp(args.hpp)
        sha = sha256_file(args.steamclient)
    except (OSError, ValueError) as e:
        print("ERROR: %s" % e, file=sys.stderr)
        return 1

    result = {
        "steamclient_sha256": sha,
        "hooks": {},          # name -> {label, status, count, rvas}
        "finder": {},         # anchor -> {status, ...}
        "blocking": [],       # display names of blocking failures
        "noncritical_moved": [],        # display names of moved non-criticals
        "noncritical_moved_consts": [], # patterns.hpp consts of the above (for --only)
        "caps": {},           # cap token -> "ok" | "moved" (all non-criticals)
        "caps_str": "",       # "shader=ok reconcile=moved" for the updates.yaml comment
        "rtti": {},           # DepotKey RTTI ground-truth (slot/rva/status)
        "rtti_byname": {},    # DepotKey slot derived from the METHOD NAME
        "gmrc_xref": {},      # GMRC's rescue path: job-name anchor + .eh_frame_hdr
        "verdict": None,
        "exit_code": None,
    }

    def record(const, label, tier):
        pat = patterns.get(const)
        if pat is None:
            # The constant vanished from patterns.hpp — treat as a hard error so
            # a rename can't silently drop a hook from the check.
            result["hooks"][label] = {"tier": tier, "status": "MISSING_FROM_HPP",
                                      "count": 0, "rvas": []}
            return "MISSING_FROM_HPP"
        rvas = scan_rvas(segments, pat)
        status = classify_hit_count(len(rvas))
        result["hooks"][label] = {
            "tier": tier, "status": status, "count": len(rvas),
            "rvas": ["0x%x" % r for r in rvas[:8]],
        }
        return status

    # 1) critical hooks — must be UNIQUE
    for const, label in CRITICAL.items():
        if record(const, label, "critical") != "UNIQUE":
            result["blocking"].append(label)

    # 1b) DepotKey RTTI ground-truth — mirror Rtti::ResolveVtableSlotBySignature:
    # find CConfigStore's vtable and confirm EXACTLY ONE slot's prologue matches
    # kDepotKeyFnPattern (the runtime's primary resolution), recording the derived
    # slot for reorder-drift detection. Zero / multiple / walk-failure => BLOCKING.
    dk_pat = patterns.get(RTTI_DEPOTKEY["const"])
    if dk_pat is None:
        result["rtti"] = {"status": "PATTERN_MISSING_FROM_HPP"}
        result["blocking"].append("DepotKey-RTTI:pattern-missing")
    else:
        matches, note = rtti_derive_slot(
            args.steamclient, RTTI_DEPOTKEY["class"], dk_pat, RTTI_DEPOTKEY["max_slots"])
        if matches is None:
            result["rtti"] = {"status": "VTABLE_WALK_FAILED", "note": note}
            result["blocking"].append("DepotKey-RTTI:walk-failed(%s)" % note)
        elif len(matches) == 1:
            slot, fn_rva = matches[0]
            pat_rvas = result["hooks"].get(RTTI_DEPOTKEY["label"], {}).get("rvas", [])
            result["rtti"] = {
                "status": "UNIQUE",
                "class": RTTI_DEPOTKEY["class"],
                "slot": slot,
                "rva": "0x%x" % fn_rva,
                # When DepotKey's .text pattern is UNIQUE the two must agree by
                # construction (same signature); record it as a corroboration.
                "agrees_with_pattern": bool(pat_rvas) and pat_rvas[0] == ("0x%x" % fn_rva),
            }
        elif len(matches) == 0:
            # Vtable found, but no slot's prologue matches — the accessor is no
            # longer a CConfigStore virtual (or the pattern moved). BLOCKING.
            result["rtti"] = {"status": "NO_SLOT_MATCH", "class": RTTI_DEPOTKEY["class"]}
            result["blocking"].append("DepotKey-RTTI:no-slot-matches-pattern")
        else:
            result["rtti"] = {
                "status": "AMBIGUOUS",
                "class": RTTI_DEPOTKEY["class"],
                "slots": [{"slot": s, "rva": "0x%x" % f} for s, f in matches],
            }
            result["blocking"].append("DepotKey-RTTI:ambiguous(%d slots)" % len(matches))

    # 1c) DepotKey by NAME — the independent second opinion, and the runtime's
    # last-resort resolver. Reads no byte of the accessor, so it is the only check
    # here that survives the event which takes pattern, feed and the RTTI walk out
    # together: a recompile that moves the prologue.
    #
    # Severity, deliberately asymmetric:
    #   - the two RESOLVE and DISAGREE  -> BLOCKING. Something moved and we cannot
    #     say what; publishing a whitelist entry on that would be guessing.
    #   - by-name cannot resolve at all -> NOT blocking. What we publish (the
    #     pattern's RVA) is still correct, so the build is fine; but the runtime's
    #     parachute is dead and that must be visible. It lands in the human report,
    #     which the auto-PR embeds, so it shows up where the hash bump is reviewed.
    bn, bn_note = rtti_derive_slot_byname(
        args.steamclient, BYNAME_DEPOTKEY["map_class"], BYNAME_DEPOTKEY["method"],
        BYNAME_DEPOTKEY["impl_class"], BYNAME_DEPOTKEY["max_slots"],
        BYNAME_DEPOTKEY["max_fn_size"])
    bn["note"] = bn_note
    result["rtti_byname"] = bn
    if bn.get("status") == "UNIQUE":
        rt = result.get("rtti", {})
        if rt.get("status") == "UNIQUE":
            bn["agrees_with_rtti"] = (rt.get("slot") == bn["slot"]
                                      and rt.get("rva") == bn["rva"])
            if not bn["agrees_with_rtti"]:
                result["blocking"].append(
                    "DepotKey-byname:disagrees(pattern slot %s @ %s vs name slot %s @ %s)"
                    % (rt.get("slot"), rt.get("rva"), bn["slot"], bn["rva"]))

    # 1d) GMRC's RESCUE path. The byte pattern above is what gets published; this
    # is what the Deck falls back to when that pattern misses, so it runs in
    # precisely the situation where nothing else can catch it being wrong. Two
    # dependencies, neither validated before now: the job-name string anchor, and
    # .eh_frame_hdr (which the runtime has used to resolve the entry since
    # 2026-09-07, replacing the walk-back and its two failure modes).
    #
    # Severity:
    #   - resolves and DISAGREES with the pattern -> BLOCKING. One of the two is
    #     wrong and there is no third opinion to say which.
    #   - does not resolve at all -> NOT blocking. The published RVA comes from the
    #     pattern and is still correct, so the build is fine — but the rescue is
    #     dead and that must be visible before it is needed, not after.
    gx, gx_note = gmrc_xref_derive(args.steamclient, GMRC_XREF["string"])
    gx["note"] = gx_note
    result["gmrc_xref"] = gx
    if gx.get("status") == "UNIQUE":
        pat_rvas = result["hooks"].get(GMRC_XREF["label"], {}).get("rvas", [])
        if pat_rvas:
            gx["agrees_with_pattern"] = (pat_rvas[0] == gx["rva"])
            if not gx["agrees_with_pattern"]:
                result["blocking"].append(
                    "GMRC-xref:disagrees(pattern %s vs xref %s)"
                    % (pat_rvas[0], gx["rva"]))

    # 2) non-criticals (ShaderDepot, Reconcile) — a miss opens an issue + auto-
    # derive but still PR-able. Record per-hook capability (ok/moved) so the
    # whitelist can carry it and LumaDeck knows what a build would lose.
    for const, label in NONCRITICAL.items():
        ok = record(const, label, "noncritical") == "UNIQUE"
        token = CAP_TOKEN.get(const, label.lower())
        result["caps"][token] = "ok" if ok else "moved"
        if not ok:
            result["noncritical_moved"].append(label)
            result["noncritical_moved_consts"].append(const)
    # stable order: follow CAP_TOKEN declaration order
    result["caps_str"] = " ".join(
        "%s=%s" % (CAP_TOKEN[c], result["caps"][CAP_TOKEN[c]])
        for c in NONCRITICAL if CAP_TOKEN.get(c) in result["caps"])

    # 3) LoadPackage — diagnostic-only, multi-match expected; never blocks
    for const, label in DIAGNOSTIC.items():
        record(const, label, "diagnostic")

    # 4a) finder cache-access idiom (0xc58)
    idiom = verify_cache_idiom(segments)
    if idiom:
        result["finder"]["cache_idiom"] = {
            "status": "PRESENT",
            "sites": [{"rva": "0x%x" % r, "disp32": "0x%x" % (d & 0xFFFFFFFF)}
                      for r, d in idiom[:8]],
        }
    else:
        result["finder"]["cache_idiom"] = {"status": "NOT_FOUND"}
        result["blocking"].append("finder:cache_idiom(0x%x)" % CACHE_ROOT_OFFSET)

    # 4b) GMRC prologue tail
    tail_rvas = scan_rvas(segments, GMRC_PROLOGUE_TAIL)
    tail_status = classify_hit_count(len(tail_rvas))
    result["finder"]["gmrc_tail"] = {
        "status": tail_status, "count": len(tail_rvas),
        "rvas": ["0x%x" % r for r in tail_rvas[:8]],
    }
    # NOT_FOUND blocks (DeriveGotBase can't work). AMBIGUOUS is only a warning:
    # DeriveGotBase finds the right one at runtime, but flag it for a tighter
    # anchor — it does not block the whitelist.
    if tail_status == "NOT_FOUND":
        result["blocking"].append("finder:gmrc_tail")

    # ── verdict + exit code ──────────────────────────────────────────────────
    if result["blocking"]:
        result["verdict"] = "BLOCKING"
        result["exit_code"] = 3
    elif result["noncritical_moved"]:
        result["verdict"] = "NONCRITICAL_MOVED"
        result["exit_code"] = 2
    else:
        result["verdict"] = "CLEAN"
        result["exit_code"] = 0

    # ── human report ─────────────────────────────────────────────────────────
    print("steamclient.so SHA-256: %s" % sha)
    print("patterns.hpp:           %s" % args.hpp)
    print("")
    for label, info in result["hooks"].items():
        rva = (" @ " + info["rvas"][0]) if info["rvas"] else ""
        extra = ""
        if info["tier"] == "diagnostic":
            extra = "  (diagnostic-only; does not block)"
        elif info["tier"] == "noncritical":
            extra = "  (non-critical)"
        print("  %-12s %-13s%s%s" % (label, info["status"], rva, extra))
    ci = result["finder"]["cache_idiom"]
    print("  %-12s %s" % ("cache_idiom", ci["status"]))
    gt = result["finder"]["gmrc_tail"]
    print("  %-12s %s (%d)" % ("gmrc_tail", gt["status"], gt["count"]))
    rt = result.get("rtti", {})
    if rt.get("status") == "UNIQUE":
        print("  %-12s slot %d @ %s  (agrees-with-pattern=%s)"
              % ("DepotKey-RTTI", rt["slot"], rt["rva"], rt["agrees_with_pattern"]))
    elif rt:
        print("  %-12s %s" % ("DepotKey-RTTI", rt.get("status")))
    gx = result.get("gmrc_xref", {})
    if gx.get("status") == "UNIQUE":
        eh = gx.get("eh_frame", {})
        print("  %-12s @ %s  (agrees-with-pattern=%s, fn %d B, eh_frame %s fns)"
              % ("GMRC-xref", gx["rva"], gx.get("agrees_with_pattern"),
                 gx.get("fn_size", 0), eh.get("count", "?")))
    elif gx:
        # Not blocking: what is published comes from the pattern. But the Deck
        # falls back to this, so a dead rescue must not pass unnoticed.
        print("  %-12s %s  (%s)  <- runtime rescue unavailable on this build"
              % ("GMRC-xref", gx.get("status"), gx.get("note")))
    bn = result.get("rtti_byname", {})
    if bn.get("status") == "UNIQUE":
        extra = ""
        if len(bn.get("overloads", [])) > 1:
            extra = "  overloads=%s" % bn["overloads"]
        print("  %-12s slot %d @ %s  (agrees-with-rtti=%s)%s"
              % ("DepotKey-name", bn["slot"], bn["rva"],
                 bn.get("agrees_with_rtti"), extra))
    elif bn:
        # Not blocking: the published RVA is still the pattern's. But the runtime
        # falls back to this resolver, so a dead one must not pass unnoticed.
        print("  %-12s %s  (%s)  <- runtime fallback unavailable on this build"
              % ("DepotKey-name", bn.get("status"), bn.get("note")))
    print("")
    print("VERDICT: %s (exit %d)" % (result["verdict"], result["exit_code"]))
    if result["blocking"]:
        print("  blocking: %s  -> open issue (A.2/C), do NOT whitelist" %
              ", ".join(result["blocking"]))
    if result["noncritical_moved"]:
        print("  shader/non-critical moved: %s  -> PR the hash AND open issue" %
              ", ".join(result["noncritical_moved"]))
    if result["verdict"] == "CLEAN":
        print("  -> A.1 hash bump: PR the hash to res/updates.yaml, no release.")

    if args.json:
        with open(args.json, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)

    # Emit the RVA feed file for whitelist-able builds only (a BLOCKING build is
    # never trusted, so publishing its RVAs would be pointless/misleading).
    if args.emit_rvas and result["verdict"] != "BLOCKING":
        p = emit_rvas_file(result, args.emit_rvas, args.steam_version)
        print("Emitted RVA feed: %s" % p)

    return result["exit_code"]


if __name__ == "__main__":
    sys.exit(main())
